/** @typedef {import('../types.js').MergeDocument} MergeDocument */

/** @type {MergeDocument} */
export const mainControllerDocument = {
    path: 'src/main_controller.ts',
    baseBranch: 'main',
    incomingBranch: 'origin/feature-session-lifecycle',
    blocks: [
        { id: 'ch-init', startLine: 15, endLine: 18, label: 'Connection initialization', variant: 'change' },
        { id: 'c1', startLine: 20, endLine: 23, label: 'Profile export signature' },
        { id: 'c2', startLine: 35, endLine: 35, label: 'Session timeout constant' },
        { id: 'c3', startLine: 43, endLine: 44, label: 'Error handler return type' },
    ],
    rows: [
        { local: '/**', incoming: '/**' },
        { local: ' * Main controller — orchestrates auth, profile, and realtime channels.', incoming: ' * Main controller — orchestrates auth, profile, and realtime channels.' },
        { local: ' * @module main_controller', incoming: ' * @module main_controller' },
        { local: ' */', incoming: ' */' },
        { local: '', incoming: '' },
        { local: "import { useAuth } from './hooks/auth';", incoming: "import { useAuth } from './hooks/auth';" },
        { local: "import { api } from './services/api';", incoming: "import { api } from './services/api';" },
        { local: "import type { UserDTO, SessionConfig } from './types';", incoming: "import type { UserDTO, SessionConfig } from './types';" },
        { local: '', incoming: '' },
        { local: 'const DEFAULT_TIMEOUT_MS = 30_000;', incoming: 'const DEFAULT_TIMEOUT_MS = 30_000;' },
        { local: '', incoming: '' },
        { local: 'let activeSocket: WebSocket | null = null;', incoming: 'let activeSocket: WebSocket | null = null;' },
        { local: '', incoming: '' },
        { local: '/** Initializes the realtime connection for the active session. */', incoming: '/** Initializes the realtime connection for the active session. */' },
        { local: 'const initConnection = () => {', incoming: '// Old initialization removed in remote branch' },
        { local: '  console.log("Local initialization logic");', incoming: '' },
        { local: '  return socket.connect();', incoming: '' },
        { local: '};', incoming: '' },
        { local: '', incoming: '' },
        { local: 'export const updateProfile = async (data: any) => {', incoming: 'async function handleProfileUpdate(payload: UserDTO) {' },
        { local: "  const response = await api.put('/user', data);", incoming: "  const response = await api.put('/user', payload);" },
        { local: '  return response.data;', incoming: '  return response.data;' },
        { local: '};', incoming: '}' },
        { local: '', incoming: '' },
        { local: 'export function disconnect(): void {', incoming: 'export function disconnect(): void {' },
        { local: '  activeSocket?.close();', incoming: '  activeSocket?.close();' },
        { local: '  activeSocket = null;', incoming: '  activeSocket = null;' },
        { local: '}', incoming: '}' },
        { local: '', incoming: '' },
        { local: 'export async function refreshSession(token: string): Promise<SessionConfig> {', incoming: 'export async function refreshSession(token: string): Promise<SessionConfig> {' },
        { local: "  const response = await api.post<SessionConfig>('/session/refresh', { token });", incoming: "  const response = await api.post<SessionConfig>('/session/refresh', { token });" },
        { local: '  return response.data;', incoming: '  return response.data;' },
        { local: '}', incoming: '}' },
        { local: '', incoming: '' },
        { local: 'export const SESSION_TTL_MS = 30_000;', incoming: 'export const SESSION_TTL_MS = 45_000; // aligned with gateway idle timeout policy' },
        { local: '', incoming: '' },
        { local: 'export function logDiagnostic(event: string, payload: Record<string, unknown>): void {', incoming: 'export function logDiagnostic(event: string, payload: Record<string, unknown>): void {' },
        { local: '  if (import.meta.env.DEV) {', incoming: '  if (import.meta.env.DEV) {' },
        { local: '    console.debug(`[main_controller] ${event}`, payload);', incoming: '    console.debug(`[main_controller] ${event}`, payload);' },
        { local: '  }', incoming: '  }' },
        { local: '}', incoming: '}' },
        { local: '', incoming: '' },
        { local: 'export function handleApiError(err: unknown): string {', incoming: 'export function handleApiError(err: unknown): never {' },
        { local: '  return err instanceof Error ? err.message : String(err);', incoming: '  throw err instanceof Error ? err : new Error(String(err));' },
        { local: '', incoming: '' },
        { local: 'export const bootstrap = async (): Promise<void> => {', incoming: 'export const bootstrap = async (): Promise<void> => {' },
        { local: "  await refreshSession(localStorage.getItem('token') ?? '');", incoming: "  await refreshSession(localStorage.getItem('token') ?? '');" },
        { local: "  logDiagnostic('bootstrap_complete', { branch: import.meta.env.VITE_GIT_BRANCH ?? 'main' });", incoming: "  logDiagnostic('bootstrap_complete', { branch: import.meta.env.VITE_GIT_BRANCH ?? 'main' });" },
        { local: '};', incoming: '};' },
        { local: '', incoming: '' },
        { local: '// End of simulated file — merge preview shows full document context.', incoming: '// End of simulated file — merge preview shows full document context.' },
    ],
};
